# Generated by Django 3.1.7 on 2021-03-06 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.CharField(choices=[('laptop', 'LAPTOP'), ('mobile', 'MOBILE'), ('tab', 'TAB')], max_length=10)),
                ('manufacturer', models.CharField(choices=[('lenovo', 'LENOVO'), ('samsung', 'SAMSUNG'), ('acer', 'ACER'), ('macbook', 'MACBOOK'), ('huawei', 'HUAWEI'), ('hp', 'HP'), ('asus', 'ASUS'), ('nokia', 'NOKIA')], max_length=100)),
                ('serial_number', models.CharField(max_length=100)),
                ('purchased_date', models.DateField()),
                ('employee_name', models.CharField(max_length=100)),
                ('employee_mobile', models.IntegerField()),
                ('handover_date', models.DateField()),
            ],
        ),
    ]
